---
html_document: default
author: "Hajra Shahab"
date: "FALL 2021"
output:
  pdf_document:
    keep_tex: yes
  html_document:
    df_print: paged
pdf_document: default
title: "A/B Testing HW-2"
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=T,warning=F)

require("data.table")
library(data.table)
require("stargazer")
library(stargazer)
# install.packages("ggplot2")
library(ggplot2)
# install.packages("ggthemes")
library(ggthemes)
# install.packages("tidyverse")
library(tidyverse)
# install.packages("pwr")
library(pwr)
require("plm")
library(plm)
require("AER")
library(AER)

# SET YOUR WORKING DIRECTORY HERE
#setwd("//Users/hajrashahab/Documents/Fall Semester 2021 /AB Testing/Homework/Homework 2 /HW_2_Code.Rmd")

#clear environment
rm(list=ls());gc()

```

```{r}

#load dataset
MyData = fread(input='HW-2.csv', verbose = F)

```


```{r}
#Question 2a 
#define data 
length(unique(MyData$COUNTRY))
length(unique(MyData$YEAR))

```

```{r, echo=TRUE}
#Question 2b

#without time dummies 
plm_model<-plm(LCOMP~LHEXP + 
          LDALE +
          LHC + 
          LGDPC +
          factor(OECD) +
          POPDEN, data = MyData,
          index=c("COUNTRY","YEAR"),
          model="pooling")

```

```{r}

#with time dummies 
plmtd<-plm(LCOMP~LHEXP + 
          YEAR +
          LDALE +
          LHC + 
          LGDPC +
          factor(OECD) +
          POPDEN, data = MyData,
          index=c("COUNTRY","YEAR"),
          model="pooling")

stargazer(plm_model,plmtd,
          se=list(
            sqrt(diag(vcovHC(plm_model,
                             method="arellano",
                             type="HC1"))),
            sqrt(diag(vcovHC(plmtd,
                             method="arellano",
                             type="HC1")))),
          title="Panel OLS",
          type="text",
          model.numbers=FALSE,
          column.labels=c("no time dummies",
                          "time dummies"),
          omit = c("factor[(]YEAR[)]",
                   "factor[(]OECD[)]"),
          add.lines = list(c("OECD Dummies","Yes","Yes"),
                           c("Year Dummies","No","Yes"),
                           c("LDALE Control","Yes","Yes"),
                           c("LHC Control","Yes","Yes"),
                           c("LGDPC Control","Yes","Yes"),
                           c("POPDEN Control","Yes","Yes")))

```

```{r}
#Question 2c

#first-differences
plmtdfd <-plm(LCOMP~LHEXP + 
          factor(YEAR) +
          LDALE +
          LHC + 
          LGDPC +
          factor(OECD) +
          POPDEN, data = MyData,
          index=c("COUNTRY","YEAR"),
          model="fd")

stargazer(plm_model,plmtd,plmtdfd,
          se=list(
            sqrt(diag(vcovHC(plm_model,
                             method="arellano",
                             type="HC1"))),
            sqrt(diag(vcovHC(plmtd,
                             method="arellano",
                             type="HC1"))),
            sqrt(diag(vcovHC(plmtdfd,
                             method="arellano",
                             type="HC1")))),
          title="Panel OLS",
          type="text",
          model.numbers=FALSE,
          column.labels=c("no time dummies","time dummies","first-differences"),
          omit = c("factor[(]YEAR[)]",
                   "factor[(]OECD[)]"),
          add.lines = list(c("OECD Dummies","Yes","Yes","Yes"),
                           c("Year Dummies","No","Yes","Yes"),
                           c("LDALE Control","Yes","Yes","Yes"),
                           c("LHC Control","Yes","Yes","Yes"),
                           c("LGDPC Control","Yes","Yes","Yes"),
                           c("POPDEN Control","Yes","Yes","Yes")))

```

```{r}

#using fixed-effects
plmtdfe <-plm(LCOMP~LHEXP + 
          COUNTRY +
          factor(YEAR) +
          LDALE +
          LHC + 
          LGDPC +
          factor(OECD) +
          POPDEN, data = MyData,
          index=c("COUNTRY","YEAR"),
          model="within")

stargazer(plm_model,plmtd,plmtdfd,plmtdfe,
          se=list(
            sqrt(diag(vcovHC(plm_model,
                             method="arellano",
                             type="HC1"))),
            sqrt(diag(vcovHC(plmtd,
                             method="arellano",
                             type="HC1"))),
            sqrt(diag(vcovHC(plmtdfd,
                             method="arellano",
                             type="HC1"))),
            sqrt(diag(vcovHC(plmtdfe,
                             method="arellano",
                             type="HC1")))),
          title="Panel OLS",
          type="text",
          model.numbers=FALSE,
          column.labels=c("no time dummies",
                          "time dummies",
                          "first-differences",
                          "fixed-effects"),
          omit = c("factor[(]YEAR[)]",
                   "factor[(]OECD[)]"),
          add.lines = list(c("OECD Dummies","Yes","Yes","Yes","Yes","Yes"),
                           c("Year Dummies","No","Yes","Yes","Yes","Yes"),
                           c("LDALE Control","Yes","Yes","Yes","Yes","Yes"),
                           c("LHC Control","Yes","Yes","Yes","Yes","Yes"),
                           c("LGDPC Control","Yes","Yes","Yes","Yes","Yes"),
                           c("POPDEN Control","Yes","Yes","Yes","Yes","Yes")))

```